### ISSUE TITLE
Complete the TODO application - step 1

### ISSUE THREAD

**Issue by brayomumo** [brayomumo/Psychic-compendium#2]
Remaining tasks to make it fully functional:
- [x] mark task as Done(partially implemented)
- [x] list unfishined tasks
- [x] add timeline on tasks
- [x] delete tasks
