### ISSUE TITLE
Complete TODO application - step 2

### ISSUE THREAD

**Issue by brayomumo** [brayomumo/Psychic-compendium#3]
Implement following feature to make this up a complete beast:

- [ ] Implement database for persistent storage
        -  postgresql / no-sql database
- [ ] Add multi user support 
- [ ]  user registration
- [ ]  user login 
- [ ] user logout 
- [ ] user - tasks  fuctionality
